### PR TITLE
Fix issue #20 and #23

### LINKED ISSUE #20: Melody should stop Tone.Transport upon dispose
https://github.com/googleinterns/guide-doge/blob/f01fa634a0e493596aa578cb3a0124fba73ecba1/src/models/melody/melody.model.spec.ts#L21
Move line 21 **into** the `dispose()` method of `Melody`.

### PR DESCRIPTION
**Pull request by 64json**
(Branched off of #22.)
Use `window.setTimeout` instead of `Tone.Transport` to play melody. Even though it is not accurate to within milliseconds, it guarantees to never skip a note and synchronize the active indicator with playhead perfectly.

### CODE REVIEW

File: src/components/preference-group/preference-group.component.ts [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+import { BehaviorSubject } from 'rxjs';
+
+@Component({
+  selector: 'app-preference-group',
+  templateUrl: './preference-group.component.html',
+  styleUrls: ['./preference-group.component.scss'],
+})
+export class PreferenceGroupComponent {
+  @Input() title: string;
+  @Input() subject: BehaviorSubject<boolean>;
```
Comment (jnager) [inline src/components/preference-group/preference-group.component.ts:11]: How about preference$ or some other name with a bit more of an indication of what value the user can expect?

File: src/components/preference-item/preference-item.component.ts [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+import { BehaviorSubject } from 'rxjs';
+
+@Component({
+  selector: 'app-preference-item',
+  templateUrl: './preference-item.component.html',
+  styleUrls: ['./preference-item.component.scss'],
+})
+export class PreferenceItemComponent<T> {
+  @Input() name: string;
+  @Input() subject: BehaviorSubject<T>;
```
Comment (jnager) [inline src/components/preference-item/preference-item.component.ts:11]: ditto here for the naming

File: src/components/preference-group/preference-group.component.ts (hunk 1 above)
Comment (64json) [reply src/components/preference-group/preference-group.component.ts:11]: sounds good! one thing i'm worried about is is it conventionally okay to have `$` in the name of an input property?
```html
<app-preference-group [preference$]="...">
```
